
---
- name: ensure apt cache has been updated
  apt: update_cache=yes cache_valid_time=86400

- name: install supervisor
  apt: pkg={{ item }} state=installed
  with_items:
    - supervisor

- name: make sure tcp_hybla enabled
  modprobe:
    name: tcp_hybla
    state: present

- name: put sysctl conf
  copy: src=sysctl.conf
        dest=/etc/sysctl.conf
        owner=root group=root mode=0644
  notify: reload sysctl

- name: forbidden password login
  lineinfile: dest=/etc/ssh/sshd_config
              backrefs=yes
              state=present
              regexp='#PasswordAuthentication'
              line='PasswordAuthentication no'
  notify: restart sshd
