
---
- name: ensure apt cache has been updated
  apt: update_cache=yes cache_valid_time=86400

- name: set net.ipv4.ip_forward
  sysctl: name=net.ipv4.ip_forward value=1 state=present

- name: install iptables-persistent
  apt: pkg=iptables-persistent state=installed

- name: start iptables-persistent
  service: name=iptables-persistent state=started enabled=true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: start iptables-persistent
  service: name=netfilter-persistent state=started enabled=true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: forbidden password login
  lineinfile: dest=/etc/ssh/sshd_config
              backrefs=yes
              state=present
              regexp='#PasswordAuthentication'
              line='PasswordAuthentication no'
  notify: restart sshd
